#!/bin/bash

regex="[0-9]"

if [[ "$1" =~ $regex ]] ; then
	count="$1"
else
	count="10"
fi
if [ "$#" -gt 0 ]; then
    startcount=$1
else
    startcount=1
fi

echo Count is $count

for i in `seq 1 $count`
do
	java client/Sphereority -debug -nowindow -fps -botnum=$[startcount+i]&
	sleep 7
done
echo "Finished starting $count bots"
