#!/bin/bash

regex="[0-9]"

if [[ "$1" =~ $regex ]] ; then
	count="$1"
else
	count="10"
fi

echo Count is $count

for i in `seq 1 $count`
do
	java client/Sphereority -debug -nowindow -fps&
	sleep 7
done
echo "Finished starting $count bots"
